/**
 * Seed the 44 curriculum-aligned questions from the ChatGPT PDF
 * GET /api/seed-pdf?secret=<NEXTAUTH_SECRET>
 */
import { putItem, TABLES } from "@/lib/dynamodb";
import { v4 as uuidv4 } from "uuid";

const PDF_QUESTIONS = [
  // ─── MATHS PREP ──────────────────────────────────────────────────────────────
  {
    subject: "maths", yearLevel: "prep", difficulty: 2,
    questionText: "How many counters are on the ten-frame? (Look at the picture.)",
    ttsText: "How many counters are on the ten-frame? Tap the answer.",
    answerOptions: [
      { id: "a", text: "5", imageUrl: "emoji:5️⃣", isCorrect: false },
      { id: "b", text: "6", imageUrl: "emoji:6️⃣", isCorrect: true },
      { id: "c", text: "7", imageUrl: "emoji:7️⃣", isCorrect: false },
      { id: "d", text: "8", imageUrl: "emoji:8️⃣", isCorrect: false },
    ],
    topics: ["counting", "ten-frame", "numbers-to-10"],
    explanation: "Count the filled spots on the ten-frame. There are 6.",
    hint: "Count the top row first, then the bottom row.",
    interactionType: "tap-card",
    interactionData: { assetKey: "svg:ten_frame_01", filled: [0,1,2,3,4,5] },
  },
  {
    subject: "maths", yearLevel: "prep", difficulty: 1,
    questionText: "How many dots do you see? (No counting one-by-one!)",
    ttsText: "How many dots do you see? Tap the number.",
    answerOptions: [
      { id: "a", text: "3", imageUrl: "emoji:3️⃣", isCorrect: false },
      { id: "b", text: "4", imageUrl: "emoji:4️⃣", isCorrect: true },
      { id: "c", text: "5", imageUrl: "emoji:5️⃣", isCorrect: false },
      { id: "d", text: "6", imageUrl: "emoji:6️⃣", isCorrect: false },
    ],
    topics: ["subitising", "dot-patterns", "numbers-0-5"],
    explanation: "There are 4 dots arranged like the 4 on a dice.",
    hint: "Try to see the dots as a group, like a dice face.",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "prep", difficulty: 3,
    questionText: "Tap the shape that has 3 sides.",
    ttsText: "Tap the shape that has three sides.",
    answerOptions: [
      { id: "a", text: "Triangle 🔺", imageUrl: "emoji:🔺", isCorrect: true },
      { id: "b", text: "Square 🟦", imageUrl: "emoji:🟦", isCorrect: false },
      { id: "c", text: "Circle ⭕", imageUrl: "emoji:⭕", isCorrect: false },
      { id: "d", text: "Rectangle 🟩", imageUrl: "emoji:🟩", isCorrect: false },
    ],
    topics: ["geometry", "shapes", "sides", "triangles"],
    explanation: "A triangle has 3 straight sides and 3 corners.",
    hint: "Count the straight edges. Corners help you count!",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "prep", difficulty: 4,
    questionText: "What comes next? 🟦 🟨 🟦 🟨 🟦 ___",
    ttsText: "Blue, yellow, blue, yellow, blue. What comes next? Tap the answer.",
    answerOptions: [
      { id: "a", text: "🟨 Yellow", imageUrl: "emoji:🟨", isCorrect: true },
      { id: "b", text: "🟦 Blue", imageUrl: "emoji:🟦", isCorrect: false },
      { id: "c", text: "🟥 Red", imageUrl: "emoji:🟥", isCorrect: false },
      { id: "d", text: "⭐ Star", imageUrl: "emoji:⭐", isCorrect: false },
    ],
    topics: ["patterns", "repeating-patterns", "ab-pattern"],
    explanation: "The pattern repeats blue, yellow. After blue comes yellow.",
    hint: "Say it out loud: blue, yellow, blue, yellow…",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "prep", difficulty: 5,
    questionText: "Ava has 7 balloons 🎈🎈🎈🎈🎈🎈🎈. Two fly away. How many are left?",
    ttsText: "Ava has seven balloons. Two fly away. How many balloons are left?",
    answerOptions: [
      { id: "a", text: "5", imageUrl: "emoji:5️⃣", isCorrect: true },
      { id: "b", text: "6", imageUrl: "emoji:6️⃣", isCorrect: false },
      { id: "c", text: "7", imageUrl: "emoji:7️⃣", isCorrect: false },
      { id: "d", text: "4", imageUrl: "emoji:4️⃣", isCorrect: false },
    ],
    topics: ["subtraction", "take-away", "story-problems", "numbers-to-10"],
    explanation: "Taking 2 away from 7 leaves 5. Count back: 7, 6, 5.",
    hint: "Start at 7 and count back 2: 6, 5.",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "prep", difficulty: 6,
    questionText: "You connect 3 dots with lines. What shape do you make?",
    ttsText: "You connect three dots to make a shape. What shape is it?",
    answerOptions: [
      { id: "a", text: "Triangle 🔺", imageUrl: "emoji:🔺", isCorrect: true },
      { id: "b", text: "Square 🟦", imageUrl: "emoji:🟦", isCorrect: false },
      { id: "c", text: "Circle ⭕", imageUrl: "emoji:⭕", isCorrect: false },
      { id: "d", text: "Star ⭐", imageUrl: "emoji:⭐", isCorrect: false },
    ],
    topics: ["geometry", "triangles", "spatial", "fine-motor"],
    explanation: "A triangle is made with 3 corners connected by 3 lines.",
    hint: "3 dots, 3 lines, 3 corners — that's a triangle!",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "prep", difficulty: 9,
    questionText: "The teddy 🧸 is on the floor below the table. Where is the teddy?",
    ttsText: "The teddy is on the floor below the table. Where is the teddy?",
    answerOptions: [
      { id: "a", text: "On the table", imageUrl: "emoji:🪑", isCorrect: false },
      { id: "b", text: "Under the table", imageUrl: "emoji:🧸", isCorrect: true },
      { id: "c", text: "Next to the table", imageUrl: "emoji:➡️", isCorrect: false },
      { id: "d", text: "Inside the table", imageUrl: "emoji:📦", isCorrect: false },
    ],
    topics: ["position", "spatial-language", "under-over"],
    explanation: "Below the table means under the table — the teddy is under it.",
    hint: "Below means lower than something else.",
    interactionType: "tap-card",
  },

  // ─── MATHS YEAR 3 ────────────────────────────────────────────────────────────
  {
    subject: "maths", yearLevel: "year3", difficulty: 5,
    questionText: "How many dots are in the array? (3 rows of 4)",
    ttsText: "How many dots in an array with three rows of four? Tap the answer.",
    answerOptions: [
      { id: "a", text: "7", imageUrl: "emoji:7️⃣", isCorrect: false },
      { id: "b", text: "12", imageUrl: "emoji:1️⃣2️⃣", isCorrect: true },
      { id: "c", text: "24", imageUrl: "emoji:2️⃣4️⃣", isCorrect: false },
      { id: "d", text: "10", imageUrl: "emoji:🔟", isCorrect: false },
    ],
    topics: ["multiplication", "arrays", "facts-3", "facts-4"],
    explanation: "3 rows of 4 is 3 × 4 = 12.",
    hint: "Think: 4 + 4 + 4.",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "year3", difficulty: 6,
    questionText: "Kai has 15 grapes 🍇. He shares them equally into 5 bowls. How many in each bowl?",
    ttsText: "Kai has fifteen grapes. He shares them into five equal bowls. How many in each bowl?",
    answerOptions: [
      { id: "a", text: "2", imageUrl: "emoji:2️⃣", isCorrect: false },
      { id: "b", text: "3", imageUrl: "emoji:3️⃣", isCorrect: true },
      { id: "c", text: "5", imageUrl: "emoji:5️⃣", isCorrect: false },
      { id: "d", text: "10", imageUrl: "emoji:🔟", isCorrect: false },
    ],
    topics: ["division", "equal-sharing", "related-facts", "facts-5"],
    explanation: "15 divided into 5 equal groups = 3 in each group.",
    hint: "If there are 5 bowls, try placing one grape in each until you run out.",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "year3", difficulty: 8,
    questionText: "Tap the clock that shows 3:45.",
    ttsText: "Tap the clock that shows three forty-five. That is quarter to four.",
    answerOptions: [
      { id: "a", text: "3:45 ✅", imageUrl: "emoji:🕓", isCorrect: true },
      { id: "b", text: "3:15", imageUrl: "emoji:🕒", isCorrect: false },
      { id: "c", text: "4:45", imageUrl: "emoji:🕟", isCorrect: false },
      { id: "d", text: "3:50", imageUrl: "emoji:🕒", isCorrect: false },
    ],
    topics: ["time", "reading-time", "minutes", "quarters"],
    explanation: "At 3:45 the minute hand points to 9 (45 minutes) and the hour hand is near 4.",
    hint: "Look for the minute hand on the 9.",
    interactionType: "clock-tap",
  },
  {
    subject: "maths", yearLevel: "year3", difficulty: 7,
    questionText: "3 of 8 equal boxes are shaded. What fraction is shaded?",
    ttsText: "Three of eight equal boxes are shaded. What fraction is shaded?",
    answerOptions: [
      { id: "a", text: "3/8", imageUrl: "emoji:🟦", isCorrect: true },
      { id: "b", text: "3/6", imageUrl: "emoji:🟩", isCorrect: false },
      { id: "c", text: "1/8", imageUrl: "emoji:🟨", isCorrect: false },
      { id: "d", text: "5/8", imageUrl: "emoji:🟥", isCorrect: false },
    ],
    topics: ["fractions", "unit-fractions", "fractions-of-shapes"],
    explanation: "Three shaded out of eight total parts = 3/8.",
    hint: "Count total boxes first (8), then count shaded boxes (3).",
    interactionType: "fraction-shade",
  },
  {
    subject: "maths", yearLevel: "year3", difficulty: 2,
    questionText: "Tap the point on the number line that is 7.",
    ttsText: "Tap the point on the number line that is seven.",
    answerOptions: [
      { id: "a", text: "6", imageUrl: "emoji:6️⃣", isCorrect: false },
      { id: "b", text: "7", imageUrl: "emoji:7️⃣", isCorrect: true },
      { id: "c", text: "8", imageUrl: "emoji:8️⃣", isCorrect: false },
      { id: "d", text: "10", imageUrl: "emoji:🔟", isCorrect: false },
    ],
    topics: ["number-line", "counting-on", "place-value"],
    explanation: "7 is one step after 6 and one step before 8.",
    hint: "Start at 0 and count up: 1, 2, 3…",
    interactionType: "tap-numberline",
  },
  {
    subject: "maths", yearLevel: "year3", difficulty: 9,
    questionText: "Which picture shows a RIGHT angle?",
    ttsText: "Which picture shows a right angle, like the corner of a square?",
    answerOptions: [
      { id: "a", text: "Right angle (90°) ▛", imageUrl: "emoji:📐", isCorrect: true },
      { id: "b", text: "Acute angle (small)", imageUrl: "emoji:🔼", isCorrect: false },
      { id: "c", text: "Obtuse angle (wide)", imageUrl: "emoji:🔽", isCorrect: false },
      { id: "d", text: "Straight line (180°)", imageUrl: "emoji:➖", isCorrect: false },
    ],
    topics: ["geometry", "angles", "right-angle"],
    explanation: "A right angle is exactly 90 degrees — like the corner of a square.",
    hint: "A right angle looks like an L shape.",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "year3", difficulty: 10,
    questionText: "Look at the bar chart. Banana: 5, Apple: 3, Grapes: 2, Orange: 4. Which fruit got the MOST votes?",
    ttsText: "Look at the bar chart. Which fruit got the most votes?",
    answerOptions: [
      { id: "a", text: "Apple 🍎", imageUrl: "emoji:🍎", isCorrect: false },
      { id: "b", text: "Banana 🍌", imageUrl: "emoji:🍌", isCorrect: true },
      { id: "c", text: "Grapes 🍇", imageUrl: "emoji:🍇", isCorrect: false },
      { id: "d", text: "Orange 🍊", imageUrl: "emoji:🍊", isCorrect: false },
    ],
    topics: ["data", "bar-graphs", "compare"],
    explanation: "Banana has 5 votes — the tallest bar shows the most votes.",
    hint: "Find the tallest bar first.",
    interactionType: "tap-card",
  },
  {
    subject: "maths", yearLevel: "year3", difficulty: 8,
    questionText: "Pictograph: Each 🐝 = 2 points. There are 6 bees shown. How many points total?",
    ttsText: "Each bee stands for two points. There are six bees. How many points total?",
    answerOptions: [
      { id: "a", text: "10", imageUrl: "emoji:🔟", isCorrect: false },
      { id: "b", text: "12", imageUrl: "emoji:1️⃣2️⃣", isCorrect: true },
      { id: "c", text: "14", imageUrl: "emoji:1️⃣4️⃣", isCorrect: false },
      { id: "d", text: "16", imageUrl: "emoji:1️⃣6️⃣", isCorrect: false },
    ],
    topics: ["data", "pictographs", "multiplicative-thinking"],
    explanation: "6 bees × 2 points each = 12 points total.",
    hint: "Count the bees (6), then double it.",
    interactionType: "pictograph-count",
  },

  // ─── ENGLISH PREP ────────────────────────────────────────────────────────────
  {
    subject: "english", yearLevel: "prep", difficulty: 1,
    questionText: "Which word RHYMES with \"cat\"?",
    ttsText: "Which word rhymes with cat? Tap the answer.",
    answerOptions: [
      { id: "a", text: "hat 🎩", imageUrl: "emoji:🎩", isCorrect: true },
      { id: "b", text: "cup ☕", imageUrl: "emoji:☕", isCorrect: false },
      { id: "c", text: "dog 🐶", imageUrl: "emoji:🐶", isCorrect: false },
      { id: "d", text: "sun ☀️", imageUrl: "emoji:☀️", isCorrect: false },
    ],
    topics: ["phonological-awareness", "rhyming", "word-play"],
    explanation: "Cat and hat end with the same sound: /at/.",
    hint: "Say cat… now say the answers. Which one sounds the same at the end?",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "prep", difficulty: 4,
    questionText: "Listen, then tap the picture for the word: \"ship\".",
    ttsText: "Listen: ship. Tap the picture for ship.",
    answerOptions: [
      { id: "a", text: "ship 🚢", imageUrl: "emoji:🚢", isCorrect: true },
      { id: "b", text: "sheep 🐑", imageUrl: "emoji:🐑", isCorrect: false },
      { id: "c", text: "shop 🏪", imageUrl: "emoji:🏪", isCorrect: false },
      { id: "d", text: "chip 🍟", imageUrl: "emoji:🍟", isCorrect: false },
    ],
    topics: ["phonics", "listening", "minimal-pairs", "digraphs-sh"],
    explanation: "Ship starts with the /sh/ sound and means a big boat.",
    hint: "Listen to the first sound: /sh/… which picture is a ship?",
    interactionType: "audio-listen-tap",
  },
  {
    subject: "english", yearLevel: "prep", difficulty: 3,
    questionText: "Tap the word that matches the picture: 🐷",
    ttsText: "Tap the word that matches the picture of a pig.",
    answerOptions: [
      { id: "a", text: "pig", imageUrl: "emoji:🐷", isCorrect: true },
      { id: "b", text: "peg", imageUrl: "emoji:📌", isCorrect: false },
      { id: "c", text: "big", imageUrl: "emoji:🐘", isCorrect: false },
      { id: "d", text: "dig", imageUrl: "emoji:⛏️", isCorrect: false },
    ],
    topics: ["phonics", "cvc-words", "word-picture-match"],
    explanation: "The picture is a pig, spelled p-i-g.",
    hint: "Look at the first letter sound: p.",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "prep", difficulty: 5,
    questionText: "Tap the sight word: \"the\".",
    ttsText: "Tap the sight word: the.",
    answerOptions: [
      { id: "a", text: "the", imageUrl: "emoji:✅", isCorrect: true },
      { id: "b", text: "then", imageUrl: "emoji:❌", isCorrect: false },
      { id: "c", text: "they", imageUrl: "emoji:❌", isCorrect: false },
      { id: "d", text: "there", imageUrl: "emoji:❌", isCorrect: false },
    ],
    topics: ["sight-words", "high-frequency-words"],
    explanation: "\"The\" is a very common word. It has three letters: t-h-e.",
    hint: "Find the shortest word: t-h-e.",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "prep", difficulty: 7,
    questionText: "Drag the words to make a sentence. Which order is correct?",
    ttsText: "Which sentence is correct? Drag words to make: I like pizza.",
    answerOptions: [
      { id: "a", text: "I like pizza. ✅", imageUrl: "emoji:✅", isCorrect: true },
      { id: "b", text: "Like I pizza. ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "c", text: "Pizza like I. ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "d", text: "I pizza like. ❌", imageUrl: "emoji:❌", isCorrect: false },
    ],
    topics: ["sentence-building", "word-order", "writing"],
    explanation: "A sentence starts with the person (I), then the action (like), then the thing (pizza).",
    hint: "Start with \"I\".",
    interactionType: "arrange-words",
  },
  {
    subject: "english", yearLevel: "prep", difficulty: 8,
    questionText: "Which one is a QUESTION?",
    ttsText: "Which one is a question? Tap the sentence that asks something.",
    answerOptions: [
      { id: "a", text: "Where is my hat? 🎩", imageUrl: "emoji:❓", isCorrect: true },
      { id: "b", text: "I have a hat.", imageUrl: "emoji:🎩", isCorrect: false },
      { id: "c", text: "My hat!", imageUrl: "emoji:❗", isCorrect: false },
      { id: "d", text: "Hat.", imageUrl: "emoji:💬", isCorrect: false },
    ],
    topics: ["punctuation", "sentence-types", "questions"],
    explanation: "Questions end with a question mark: ?",
    hint: "Look for the question mark.",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "prep", difficulty: 9,
    questionText: "Read: \"Sam has a red ball.\" What color is the ball?",
    ttsText: "Read: Sam has a red ball. What color is the ball?",
    answerOptions: [
      { id: "a", text: "Red 🔴", imageUrl: "emoji:🔴", isCorrect: true },
      { id: "b", text: "Blue 🔵", imageUrl: "emoji:🔵", isCorrect: false },
      { id: "c", text: "Green 🟢", imageUrl: "emoji:🟢", isCorrect: false },
      { id: "d", text: "Yellow 🟡", imageUrl: "emoji:🟡", isCorrect: false },
    ],
    topics: ["reading-comprehension", "literal", "color-words"],
    explanation: "The sentence says the ball is red.",
    hint: "Point to the word that tells the color.",
    interactionType: "tap-card",
  },

  // ─── ENGLISH YEAR 3 ──────────────────────────────────────────────────────────
  {
    subject: "english", yearLevel: "year3", difficulty: 3,
    questionText: "Choose the correct plural: 1 fox, 2 _____.",
    ttsText: "Choose the correct plural. One fox, two what?",
    answerOptions: [
      { id: "a", text: "foxes 🦊🦊", imageUrl: "emoji:🦊", isCorrect: true },
      { id: "b", text: "foxs", imageUrl: "emoji:❌", isCorrect: false },
      { id: "c", text: "fox", imageUrl: "emoji:🦊", isCorrect: false },
      { id: "d", text: "foxis", imageUrl: "emoji:❌", isCorrect: false },
    ],
    topics: ["spelling", "plurals", "suffixes-es"],
    explanation: "Words ending in x usually add -es: foxes.",
    hint: "Say it: one fox… two foxes.",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "year3", difficulty: 7,
    questionText: "Which word has the prefix \"un-\" meaning \"not\"?",
    ttsText: "Which word has the prefix un- meaning not?",
    answerOptions: [
      { id: "a", text: "unhappy 😟", imageUrl: "emoji:😟", isCorrect: true },
      { id: "b", text: "redo 🔁", imageUrl: "emoji:🔁", isCorrect: false },
      { id: "c", text: "runner 🏃", imageUrl: "emoji:🏃", isCorrect: false },
      { id: "d", text: "happy 😊", imageUrl: "emoji:😊", isCorrect: false },
    ],
    topics: ["morphology", "prefixes", "vocabulary"],
    explanation: "Un- means not. Unhappy = not happy.",
    hint: "Look for the little part at the start: un-.",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "year3", difficulty: 6,
    questionText: "Which sentence is a COMPOUND sentence?",
    ttsText: "Which sentence is a compound sentence with two ideas joined by a connecting word?",
    answerOptions: [
      { id: "a", text: "I ran home, and I drank water. 🏃💧", imageUrl: "emoji:🏃", isCorrect: true },
      { id: "b", text: "I ran home.", imageUrl: "emoji:🏃", isCorrect: false },
      { id: "c", text: "And I drank water.", imageUrl: "emoji:💧", isCorrect: false },
      { id: "d", text: "Ran home I water.", imageUrl: "emoji:❌", isCorrect: false },
    ],
    topics: ["grammar", "sentences", "compound-sentences", "conjunctions"],
    explanation: "A compound sentence joins two complete ideas with a conjunction like and, but, or so.",
    hint: "Look for two parts that could each stand alone.",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "year3", difficulty: 8,
    questionText: "Read: \"Lena grabbed her umbrella. Dark clouds filled the sky.\" Why did Lena grab her umbrella?",
    ttsText: "Lena grabbed her umbrella. Dark clouds filled the sky. Why did Lena grab her umbrella?",
    answerOptions: [
      { id: "a", text: "It might rain 🌧️", imageUrl: "emoji:🌧️", isCorrect: true },
      { id: "b", text: "It was snowing ❄️", imageUrl: "emoji:❄️", isCorrect: false },
      { id: "c", text: "She wanted to fly 🪂", imageUrl: "emoji:🪂", isCorrect: false },
      { id: "d", text: "She was at the beach 🏖️", imageUrl: "emoji:🏖️", isCorrect: false },
    ],
    topics: ["reading-comprehension", "inferential", "cause-and-effect"],
    explanation: "Dark clouds are a clue that rain is coming — so an umbrella helps.",
    hint: "Use clues in the text: dark clouds usually mean…",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "year3", difficulty: 5,
    questionText: "\"Big\" means the same as…",
    ttsText: "Big means the same as which word? Tap the answer.",
    answerOptions: [
      { id: "a", text: "large 🦣", imageUrl: "emoji:🦣", isCorrect: true },
      { id: "b", text: "tiny 🐜", imageUrl: "emoji:🐜", isCorrect: false },
      { id: "c", text: "slow 🐢", imageUrl: "emoji:🐢", isCorrect: false },
      { id: "d", text: "cold 🧊", imageUrl: "emoji:🧊", isCorrect: false },
    ],
    topics: ["vocabulary", "synonyms"],
    explanation: "Large means big — they are synonyms.",
    hint: "Think of big and large as the same size word.",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "year3", difficulty: 9,
    questionText: "Which order makes a clear paragraph? (Found puppy / Checked tag / Helped it home)",
    ttsText: "Put these events in order: found a puppy, checked its tag, helped it get home.",
    answerOptions: [
      { id: "a", text: "Found → Checked tag → Home ✅", imageUrl: "emoji:✅", isCorrect: true },
      { id: "b", text: "Checked tag → Home → Found ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "c", text: "Home → Found → Checked tag ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "d", text: "Found → Home → Checked tag ❌", imageUrl: "emoji:❌", isCorrect: false },
    ],
    topics: ["writing", "paragraphs", "sequencing"],
    explanation: "A good paragraph puts events in an order that makes sense.",
    hint: "What happened first? What happened last?",
    interactionType: "drag-sort",
  },
  {
    subject: "english", yearLevel: "year3", difficulty: 8,
    questionText: "Which word is spelled correctly?",
    ttsText: "Which word is spelled correctly? Tap the correct spelling.",
    answerOptions: [
      { id: "a", text: "important ✅", imageUrl: "emoji:⭐", isCorrect: true },
      { id: "b", text: "importint ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "c", text: "imporant ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "d", text: "inportant ❌", imageUrl: "emoji:❌", isCorrect: false },
    ],
    topics: ["spelling", "multisyllabic-words", "editing"],
    explanation: "The correct spelling is important.",
    hint: "Look for the 'im' at the start and 'tant' at the end.",
    interactionType: "tap-card",
  },
  {
    subject: "english", yearLevel: "year3", difficulty: 4,
    questionText: "Match the words to the pictures: QUIET 🤫 and LOUD 📣",
    ttsText: "Match the words to the pictures. Quiet means soft sound. Loud means big sound.",
    answerOptions: [
      { id: "a", text: "quiet=🤫, loud=📣 ✅", imageUrl: "emoji:🤫", isCorrect: true },
      { id: "b", text: "quiet=📣, loud=🤫 ❌", imageUrl: "emoji:📣", isCorrect: false },
      { id: "c", text: "quiet=🤫, loud=🤫 ❌", imageUrl: "emoji:🤫", isCorrect: false },
      { id: "d", text: "quiet=📣, loud=📣 ❌", imageUrl: "emoji:📣", isCorrect: false },
    ],
    topics: ["vocabulary", "antonyms", "matching"],
    explanation: "Quiet = whispering 🤫. Loud = megaphone 📣.",
    hint: "Quiet is a soft sound. Loud is a big sound.",
    interactionType: "match-pairs",
  },

  // ─── SCIENCE PREP ────────────────────────────────────────────────────────────
  {
    subject: "science", yearLevel: "prep", difficulty: 1,
    questionText: "Which animal has FEATHERS?",
    ttsText: "Which animal has feathers? Tap the answer.",
    answerOptions: [
      { id: "a", text: "Bird 🐦", imageUrl: "emoji:🐦", isCorrect: true },
      { id: "b", text: "Cat 🐱", imageUrl: "emoji:🐱", isCorrect: false },
      { id: "c", text: "Fish 🐟", imageUrl: "emoji:🐟", isCorrect: false },
      { id: "d", text: "Snake 🐍", imageUrl: "emoji:🐍", isCorrect: false },
    ],
    topics: ["living-things", "external-features", "classification"],
    explanation: "Birds have feathers. Cats have fur, fish have scales, snakes have scales.",
    hint: "Feathers help birds fly and keep warm.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "prep", difficulty: 4,
    questionText: "Which object will ROLL best down a ramp?",
    ttsText: "Which object will roll best down a ramp? Tap the answer.",
    answerOptions: [
      { id: "a", text: "Ball ⚽", imageUrl: "emoji:⚽", isCorrect: true },
      { id: "b", text: "Book 📘", imageUrl: "emoji:📘", isCorrect: false },
      { id: "c", text: "Box 📦", imageUrl: "emoji:📦", isCorrect: false },
      { id: "d", text: "Brick 🧱", imageUrl: "emoji:🧱", isCorrect: false },
    ],
    topics: ["movement", "shape", "rolling"],
    explanation: "Round objects roll best. A ball is round.",
    hint: "Round things roll. Flat things slide.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "prep", difficulty: 7,
    questionText: "Which material is best to keep you DRY in the rain?",
    ttsText: "Which material is best to keep you dry in the rain?",
    answerOptions: [
      { id: "a", text: "Plastic 🧥", imageUrl: "emoji:🧥", isCorrect: true },
      { id: "b", text: "Paper 📄", imageUrl: "emoji:📄", isCorrect: false },
      { id: "c", text: "Sponge 🧽", imageUrl: "emoji:🧽", isCorrect: false },
      { id: "d", text: "Towel 🧻", imageUrl: "emoji:🧻", isCorrect: false },
    ],
    topics: ["materials", "properties", "waterproof"],
    explanation: "Plastic is waterproof — water cannot soak through it.",
    hint: "Waterproof means water does not soak in.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "prep", difficulty: 3,
    questionText: "Drag each thing into the right group. 🌳 is a…",
    ttsText: "Is a tree a plant or an animal? Tap the correct answer.",
    answerOptions: [
      { id: "a", text: "Plant 🌱", imageUrl: "emoji:🌱", isCorrect: true },
      { id: "b", text: "Animal 🐾", imageUrl: "emoji:🐾", isCorrect: false },
      { id: "c", text: "Rock 🪨", imageUrl: "emoji:🪨", isCorrect: false },
      { id: "d", text: "Water 💧", imageUrl: "emoji:💧", isCorrect: false },
    ],
    topics: ["living-things", "plants-animals", "classification"],
    explanation: "A tree is a plant. Plants grow from the ground and make their own food.",
    hint: "Plants grow from the ground. Animals move to find food.",
    interactionType: "drag-to-bins",
  },
  {
    subject: "science", yearLevel: "prep", difficulty: 9,
    questionText: "Which one is an OBSERVATION?",
    ttsText: "Which one is an observation? Tap the sentence you could see or measure.",
    answerOptions: [
      { id: "a", text: "The leaf is green. 🍃", imageUrl: "emoji:🍃", isCorrect: true },
      { id: "b", text: "Leaves are the best! ⭐", imageUrl: "emoji:⭐", isCorrect: false },
      { id: "c", text: "The leaf is happy. 🙂", imageUrl: "emoji:🙂", isCorrect: false },
      { id: "d", text: "The leaf will never change. ♾️", imageUrl: "emoji:♾️", isCorrect: false },
    ],
    topics: ["science-inquiry", "observation", "claims"],
    explanation: "An observation is something you can notice with your senses. You can see a leaf is green.",
    hint: "Can you see it, hear it, feel it, or measure it?",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "prep", difficulty: 10,
    questionText: "A toy car rolls farther with a harder push. What is the BEST test to check this?",
    ttsText: "What is the best way to test if a harder push makes a toy car roll farther?",
    answerOptions: [
      { id: "a", text: "Use the same ramp; change only the push. ✅", imageUrl: "emoji:✅", isCorrect: true },
      { id: "b", text: "Use different ramps every time. ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "c", text: "Change the car, ramp, and push. ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "d", text: "Don't measure how far it goes. ❌", imageUrl: "emoji:❌", isCorrect: false },
    ],
    topics: ["science-inquiry", "fair-test", "prediction"],
    explanation: "A fair test changes ONE thing and keeps everything else the same.",
    hint: "Fair test: change ONE thing.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "prep", difficulty: 6,
    questionText: "Which object is made of METAL?",
    ttsText: "Which object is made of metal? Tap the answer.",
    answerOptions: [
      { id: "a", text: "Key 🔑", imageUrl: "emoji:🔑", isCorrect: true },
      { id: "b", text: "Banana 🍌", imageUrl: "emoji:🍌", isCorrect: false },
      { id: "c", text: "Teddy bear 🧸", imageUrl: "emoji:🧸", isCorrect: false },
      { id: "d", text: "Leaf 🍃", imageUrl: "emoji:🍃", isCorrect: false },
    ],
    topics: ["materials", "identify-materials", "everyday-objects"],
    explanation: "Keys are usually made of metal — metal is hard and shiny.",
    hint: "Metal feels hard and strong, like a key.",
    interactionType: "tap-card",
  },

  // ─── SCIENCE YEAR 3 ──────────────────────────────────────────────────────────
  {
    subject: "science", yearLevel: "year3", difficulty: 2,
    questionText: "Which is NON-LIVING?",
    ttsText: "Which is non-living? Tap the thing that does not grow or need food and water.",
    answerOptions: [
      { id: "a", text: "Rock 🪨", imageUrl: "emoji:🪨", isCorrect: true },
      { id: "b", text: "Tree 🌳", imageUrl: "emoji:🌳", isCorrect: false },
      { id: "c", text: "Bird 🐦", imageUrl: "emoji:🐦", isCorrect: false },
      { id: "d", text: "Frog 🐸", imageUrl: "emoji:🐸", isCorrect: false },
    ],
    topics: ["living-vs-nonliving", "classification"],
    explanation: "A rock is non-living — it does not grow, eat, or reproduce.",
    hint: "Living things need water and food.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "year3", difficulty: 4,
    questionText: "Put the frog life cycle in order: eggs 🥚, tadpole 🐟, frog 🐸",
    ttsText: "Drag the frog life cycle into order: eggs, tadpole, frog.",
    answerOptions: [
      { id: "a", text: "Eggs → Tadpole → Frog ✅", imageUrl: "emoji:🥚", isCorrect: true },
      { id: "b", text: "Frog → Eggs → Tadpole ❌", imageUrl: "emoji:🐸", isCorrect: false },
      { id: "c", text: "Tadpole → Frog → Eggs ❌", imageUrl: "emoji:🐟", isCorrect: false },
      { id: "d", text: "Eggs → Frog → Tadpole ❌", imageUrl: "emoji:🥚", isCorrect: false },
    ],
    topics: ["life-cycles", "animals", "sequencing"],
    explanation: "Frogs start as eggs, grow into tadpoles, then become frogs.",
    hint: "What comes first: eggs or frog?",
    interactionType: "drag-sort",
  },
  {
    subject: "science", yearLevel: "year3", difficulty: 6,
    questionText: "Which is a MINERAL?",
    ttsText: "Which is a mineral? Tap the answer.",
    answerOptions: [
      { id: "a", text: "Quartz 💎", imageUrl: "emoji:💎", isCorrect: true },
      { id: "b", text: "Bread 🍞", imageUrl: "emoji:🍞", isCorrect: false },
      { id: "c", text: "Leaf 🍃", imageUrl: "emoji:🍃", isCorrect: false },
      { id: "d", text: "Plastic toy 🧸", imageUrl: "emoji:🧸", isCorrect: false },
    ],
    topics: ["earth-resources", "rocks-minerals", "properties"],
    explanation: "Quartz is a mineral — a natural material found in rocks.",
    hint: "Minerals are natural materials found in rocks.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "year3", difficulty: 6,
    questionText: "Which soil drains water FASTEST?",
    ttsText: "Which soil drains water the fastest? Tap the answer.",
    answerOptions: [
      { id: "a", text: "Sandy soil 🏖️", imageUrl: "emoji:🏖️", isCorrect: true },
      { id: "b", text: "Clay soil 🟤", imageUrl: "emoji:🟤", isCorrect: false },
      { id: "c", text: "Mud 🟫", imageUrl: "emoji:🟫", isCorrect: false },
      { id: "d", text: "Wet leaves 🍂", imageUrl: "emoji:🍂", isCorrect: false },
    ],
    topics: ["soils", "properties", "water"],
    explanation: "Sandy soil has bigger spaces so water drains through faster.",
    hint: "Think about sand at the beach — water moves through it quickly.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "year3", difficulty: 7,
    questionText: "Which material is the BEST insulator to keep a hot cup from burning your hand?",
    ttsText: "Which material is the best insulator for a hot cup?",
    answerOptions: [
      { id: "a", text: "Cardboard sleeve 📦", imageUrl: "emoji:📦", isCorrect: true },
      { id: "b", text: "Metal foil 🥄", imageUrl: "emoji:🥄", isCorrect: false },
      { id: "c", text: "Glass 🪟", imageUrl: "emoji:🪟", isCorrect: false },
      { id: "d", text: "Wet paper 📄", imageUrl: "emoji:📄", isCorrect: false },
    ],
    topics: ["heat", "transfer", "materials"],
    explanation: "Cardboard slows heat transfer, protecting your hand better than metal or glass.",
    hint: "Insulators slow heat down.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "year3", difficulty: 8,
    questionText: "Ice 🧊 left in the sun will…",
    ttsText: "Ice left in the sun will do what? Tap the answer.",
    answerOptions: [
      { id: "a", text: "Melt into liquid water 💧", imageUrl: "emoji:💧", isCorrect: true },
      { id: "b", text: "Freeze more ❄️", imageUrl: "emoji:❄️", isCorrect: false },
      { id: "c", text: "Turn into rock 🪨", imageUrl: "emoji:🪨", isCorrect: false },
      { id: "d", text: "Stay ice forever ♾️", imageUrl: "emoji:♾️", isCorrect: false },
    ],
    topics: ["states-of-matter", "change-of-state", "heating"],
    explanation: "When ice gains heat energy from the sun, it melts into liquid water.",
    hint: "Heating changes ice into water.",
    interactionType: "tap-card",
  },
  {
    subject: "science", yearLevel: "year3", difficulty: 9,
    questionText: "Fair test: What is the BEST way to test which paper towel absorbs more water?",
    ttsText: "What is the best fair test to find which paper towel absorbs more water?",
    answerOptions: [
      { id: "a", text: "Use the same amount of water each time. 💧=💧 ✅", imageUrl: "emoji:✅", isCorrect: true },
      { id: "b", text: "Use different cup sizes each time. ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "c", text: "Use different amounts of water each time. ❌", imageUrl: "emoji:❌", isCorrect: false },
      { id: "d", text: "Change towel and water and time. ❌", imageUrl: "emoji:❌", isCorrect: false },
    ],
    topics: ["science-inquiry", "fair-tests", "measurement"],
    explanation: "A fair test keeps most things the same so you only change the towel type.",
    hint: "Only one thing should change: the towel type.",
    interactionType: "tap-card",
  },
] as const;

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const secret = searchParams.get("secret");

    if (secret !== process.env.NEXTAUTH_SECRET) {
      return Response.json({ error: "Unauthorized" }, { status: 401 });
    }

    let seeded = 0;
    const errors: string[] = [];

    for (const q of PDF_QUESTIONS) {
      try {
        const item = {
          pk: `${q.subject}#${q.yearLevel}`,
          questionId: uuidv4(),
          questionText: q.questionText,
          ttsText: q.ttsText,
          answerOptions: q.answerOptions,
          difficulty: q.difficulty,
          topics: [...q.topics],
          explanation: q.explanation,
          hint: q.hint,
          subject: q.subject,
          yearLevel: q.yearLevel,
          interactionType: q.interactionType,
          interactionData: ("interactionData" in q ? q.interactionData : undefined),
          cached: false,
          createdAt: new Date().toISOString(),
        };
        await putItem(TABLES.QUESTIONS, item);
        seeded++;
      } catch (err) {
        errors.push(`Failed: "${q.questionText.slice(0, 40)}"`);
      }
    }

    return Response.json({
      success: true,
      seeded,
      failed: errors.length,
      errors: errors.slice(0, 5),
      message: `Seeded ${seeded}/${PDF_QUESTIONS.length} PDF questions`,
    });
  } catch (err) {
    console.error("Seed PDF error:", err);
    return Response.json({ error: "Seed failed" }, { status: 500 });
  }
}
